version: "3.9"
services:
    yggdrasil-db:
        image: postgres:latest
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes: 
          - ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    localstack:
        image: localstack/localstack:latest
        environment:
          - SERVICES=s3
          - DATA_DIR=/tmp/localstack/data
          - AWS_ACCESS_KEY_ID=test-id
          - AWS_SECRET_ACCESS_KEY=test-key
          #- START_WEB=1
          #- PORT_WEB_UI=8080
        ports:
          - 4566:4566
          #- 8080:8080
        volumes:
            - ./aws:/docker-entrypoint-initaws.d
            - ./data:/tmp/localstack
            - ./var/run/docker.sock:/var/run/docker.sock